# Generated by Django 2.0.5 on 2018-05-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lender',
            new_name='lent_by',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='renter',
            new_name='rented_by',
        ),
    ]
