# Generated by Django 2.0.5 on 2018-05-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_item', to='api.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
